[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xno"
version = "0.1.0"

[tool.setuptools]
packages = ["xno"]

[tool.setuptools.package-dir]
"" = "xno"
